### ISSUE TITLE
PointOfInterest properties don't match json values?

### ISSUE THREAD

**Issue by jameslavery** [SteveWinward/RideWithGPS#4]
I'm using this (excellent) library to get route information to format into my own PDF format.

I'm not getting any detail for Points Of Interest. Only _lat_, _lng_, and _parent_type_ for example.\\

I think that this is because the json:

> "points_of_interest": [
>       {
>         "id": 72170238,
>         "lng": -121.64289951324463,
>         "lat": 44.459974706411096,
>         "url": null,
>         "mongo_id": null,
>         "parent_id": 36534661,
>         "parent_type": "Route",
>         "created_at": "2022-09-28T20:26:58+01:00",
>         "updated_at": "2022-09-28T20:26:58+01:00",
>         "v": 0,
>         "t": 13,
>         "n": "Camp Sherman Store",
>         "d": "Great deli. Nice supply of groceries for a smaller store.",
>         "pids": [],
>         "uid": 604434
>       },

has "n" for the _name_ property, "d" for _description_ etc.

I think we need to decorate the PointOfInterest class with [JsonPropertyName] attributes to map from json to class properties.

I'm happy to do this with a PR.

**Comment by SteveWinward** [comment]
@jameslavery  I’m happy to review and accept a PR if you submit one for the change here!

**Comment by jameslavery** [comment]
Great, thanks. I'll give it a go - testing locally first obviously.

James
________________________________

**Comment by jameslavery** [comment]
I've got a local branch ready - think you need to add me as a collaborator so I can push it and create the PR.

**Comment by SteveWinward** [comment]
@jameslavery to create a pull request, you shouldn't need contribute rights to this repo.  You should be able to make a fork of the public repo, make the changes / commits in your local forked version, then submit for a PR and that will kick it back over to me to review and approve.

More details on how to do that are outlined here,

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

Hope this helps!

**Comment by jameslavery** [comment]
Good point - had forgotten about forks. I've worked as a collaborator up to now.

Anyhow - PR created for review and (hopefully) merge.

**Comment by SteveWinward** [comment]
Thank you for the PR you just submitted, its been approved and a new nuget version has just been published.

https://github.com/SteveWinward/RideWithGPS/pull/5

https://www.nuget.org/packages/RideWithGPS/2.0.2
